equity4profit:
  categories:
    S40:
# Starting personal Portfolio for testing...
      - BANKINDIA
      - BHEL
      - COALINDIA
      - FEDERALBNK
      - JKTYRE
# Ending personal Portfolio for testing...
      - HDFCBANK
      - ICICIBANK
      - KOTAKBANK
      - HDFCAMC
      - BAJFINANCE
      - ICICIGI
      - HDFCLIFE
      - BAJAJFINSV
      - ICICIPRULI
      - NAM-INDIA
      - PGHH
      - MARICO
      - COLPAL
      - HINDUNILVR
      - BAJAJHLDNG
      - DABUR
      - NESTLEIND
      - ITC
      - ASIANPAINT
      - BERGEPAINT
      - AKZOINDIA
      - TITAN
      - BATAINDIA
      - PAGEIND
      - WHIRLPOOL
      - HAVELLS
      - TCS
      - INFY
      - HCLTECH
      - ABBOTINDIA
      - GLAXO
      - SANOFI
      - PFIZER
      - PIDILITIND
      - GILLETTE
      - NIFTYBEES
      - BANKBEES
      - GOLDBEES
    S40NEXT:
      - 3MINDIA
      - ASTRAZEN
      - AVANTIFEED
      - BAYERCROP
      - BOSCHLTD
      - CAPLIPOINT
      - CERA
      - DIXON
      - EICHERMOT
      - ERIS
      - FINCABLES
      - FINEORG
      - GODREJCP
      - HONAUT
      - ISEC
      - JCHAC
      - KANSAINER
      - LALPATHLAB
      - MCX
      - MOTILALOFS
      - OFSS
      - SFL
      - SIS
      - SUNTV
      - SYMPHONY
      - RAJESHEXPO
      - POLYCAB
      - RADICO
      - RELAXO
      - TASTYBITE
      - TEAMLEASE
      - TTKPRESTIG
      - UJJIVANSFB
      - VGUARD
      - VINATIORGA
      - VIPIND
    S250:
      - PFC
      - RECLTD
      - SHRIRAMFIN
      - IRFC
      - LICHSGFIN
      - MUTHOOTFIN
      - ABCAPITAL
      - CHOLAFIN
      - AIIL
      - LTF
      - JIOFIN
      - HUDCO
      - MANAPPURAM
      - BAJAJHFL
      - CHOLAHLDNG
      - PNBHOUSING
      - SUNDARMFIN
      - IREDA
      - SBICARD
      - M&MFIN
      - IIFL
      - TVSHLTD
      - FIVESTAR
      - 360ONE
      - ABSLAMC
      - UTIAMC
      - AADHARHFC
      - CANFINHOME
      - CREDITACC
      - APTUS
      - MAHSCOOTER
      - AAVAS
      - JMFINANCIL
      - JPOLYINVST
      - JINDALPHOT
      - TATAINVEST
      - JSWHL
      - PNBGILTS
      - MFSL
      - HYUNDAI
      - ABB
      - BRITANNIA
      - CIPLA
      - BPCL
      - DRREDDY
      - TORNTPHARM
      - UNITDSPR
      - MANKIND
      - ZYDUSLIFE
      - CGPOWER
      - PERSISTENT
      - INDUSTOWER
      - MAZDOCK
      - SOLARINDS
      - HEROMOTOCO
      - CUMMINSIND
      - HINDPETRO
      - SUZLON
      - LLOYDSME
      - WAAREEENER
      - ATGL
      - TIINDIA
      - IRCTC
      - COFORGE
      - SUPREMEIND
      - COROMANDEL
      - NMDC
      - MPHASIS
      - PIIND
      - LTTS
      - JSL
      - SCHAEFFLER
      - PREMIERENE
      - GVT&D
      - PETRONET
      - CRISIL
      - BDL
      - APARINDS
      - APLAPOLLO
      - ASTRAL
      - BLUESTARCO
      - KEI
      - TATAELXSI
      - KPITTECH
      - COCHINSHIP
      - SONACOMS
      - AJANTPHARM
      - GUJGASLTD
      - TATATECH
      - KPRMILL
      - CDSL
      - IKS
      - DEEPAKNTR
      - AIAENG
      - AIIL
      - MANYAVAR
      - IGL
      - JBCHEPHARM
      - JYOTICNC
      - POLYMED
      - NH
      - EIHOTEL
      - EMAMILTD
      - MSUMI
      - CONCORDBIO
      - IGIL
      - MRPL
      - CARBORUNIV
      - SUMICHEM
      - GODFRYPHLP
      - NEWGEN
      - ANGELONE
      - NATCOPHARM
      - KFINTECH
      - TRITURBINE
      - NBCC
      - RATNAMANI
      - CAMS
      - ZFCVINDIA
      - ABSLAMC
      - BASF
      - SKFINDIA
      - TIMKEN
      - ZENTEC
      - GRINDWELL
      - GSPL
      - WELCORP
      - CYIENT
      - CHAMBLFERT
      - TBOTEK
      - JWL
      - CASTROLIND
      - BLS
      - AFCONS
      - BIKAJI
      - ZENSARTECH
      - ANANDRATHI
      - NEULANDLAB
      - ELGIEQUIP
      - SCHNEIDER
      - SONATSOFTW
      - KAJARIACER
      - VENTIVE
      - DOMS
      - GRSE
      - ECLERX
      - KIRLOSBROS
      - JINDALSAW
      - CELLO
      - GRAVITA
      - UTIAMC
      - NCC
      - ACE
      - RRKABEL
      - JAIBALAJI
      - HBLENGINE
      - CLEAN
      - SHAKTIPUMP
      - BSOFT
      - IEX
      - INDGN
      - JYOTHYLAB
      - EIDPARRY
      - BBTC
      - TITAGARH
      - INDIAMART
      - LTFOODS
      - PRAJIND
      - CEATLTD
      - INTELLECT
      - ELECON
      - RITES
      - KSB
      - GPIL
      - MGL
      - GLS
      - SPLPETRO
      - SAFARI
      - INGERRAND
      - RAILTEL
      - MARKSANS
      - PRUDENT
      - HAPPSTMNDS
      - USHAMART
      - JLHL
      - RAYMOND
      - BBOX
      - REDTAPE
      - CHOICEIN
      - BLUEJET
      - GANESHHOUC
      - INOXINDIA
      - HAPPYFORGE
      - ENGINERSIN
      - IONEXCHANG
      - KNRCON
      - ITDCEM
      - TIPSMUSIC
      - TANLA
      - PGHL
      - ASKAUTOLTD
      - KPIGREEN
      - SHRIPISTON
      - CHENNPETRO
      - MANINFRA
      - AURIONPRO
      - HGINFRA
      - KIRLPNU
      - MAHSEAMLES
      - FORCEMOT
      - IIFLCAPS
      - VOLTAMP
      - PNGJL
      - VESUVIUS
      - DBREALTY
      - ROUTE
      - ESABINDIA
      - GPPL
      - POWERMECH
      - TRANSRAILL
      - ASHOKA
      - TI
      - GARFIBRES
      - ACI
      - CMSINFO
      - PGIL
      - NESCO
      - DODLA
      - JKPAPER
      - GHCL
      - PRICOLLTD
      - BANCOINDIA
      - GABRIEL
      - NIITMTS
      - DHANUKA
      - KOVAI
      - SHAREINDIA
      - ICRA
      - AHLUCONT
      - CEIGALL
      - SUPRIYA
      - SHARDAMOTR
      - VSTIND
      - SURYAROSNI
      - GULFOILLUB
      - EASEMYTRIP
      - DBCORP
      - STYRENIX
      - ROLEXRINGS
      - IMFA
      - GOKULAGRO
      - KSCL
      - GRAUWEIL
      - EMSLIMITED
      - CIGNITITEC
      - MSTCLTD
      - RAMKY
      - SIYSIL
      - LGBBROSLTD
      - FIEMIND
      - DATAMATICS
      - WSTCSTPAPR
      - JAMNAAUTO
      - KKCL
      - MONARCH
      - BFUTILITIE
      - BEPL
      - NUCLEUS
      - AUTOAXLES
      - VADILALIND
      - SANGHVIMOV
      - PANAMAPET
      - DOLATALGO
      - SESHAPAPER
      - ANDHRAPAP
      - GMBREW
      - SANDESH
      
