equity4profit:
  categories:
    S40:
      - HDFCBANK
      - ICICIBANK
      - KOTAKBANK
      - HDFCAMC
      - BAJFINANCE
      - ICICIGI
      - HDFCLIFE
      - BAJAJFINSV
      - ICICIPRULI
      - NAM-INDIA
      - PGHH
      - MARICO
      - COLPAL
      - HINDUNILVR
      - BAJAJHLDNG
      - DABUR
      - NESTLEIND
      - ITC
      - ASIANPAINT
      - BERGEPAINT
      - AKZOINDIA
      - TITAN
      - BATAINDIA
      - PAGEIND
      - WHIRLPOOL
      - HAVELLS
      - TCS
      - INFY
      - HCLTECH
      - ABBOTINDIA
      - GLAXO
      - SANOFI
      - PFIZER
      - PIDILITIND
      - GILLETTE
      - NIFTYBEES
      - BANKBEES
      - GOLDBEES
    S40NEXT:
      - 3MINDIA
      - ASTRAZEN
      - AVANTIFEED
      - BAYERCROP
      - BOSCHLTD
      - CAPLIPOINT
      - CERA
      - DIXON
      - EICHERMOT
      - EQUITAS
      - EQUITASBNK
      - ERIS
      - FINCABLES
      - FINEORG
      - GODREJCP
      - HONAUT
      - ISEC
      - JCHAC
      - KANSAINER
      - LALPATHLAB
      - MCX
      - MOTILALOFS
      - OFSS
      - SFL
      - SIS
      - SUNTV
      - SYMPHONY
      - RAJESHEXPO
      - POLYCAB
      - RADICO
      - RELAXO
      - TASTYBITE
      - TEAMLEASE
      - TTKPRESTIG
      - UJJIVAN
      - UJJIVANSFB
      - VGUARD
      - VINATIORGA
      - VIPIND
